name: 'dq_demo'
version: '1.0.0'
config-version: 2

profile: 'dq_demo'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
docs-paths: ["docs"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  dbt_dq_tool_schema: dq_tools

on-run-start:
  - '{{ dq_tools.create_dq_issue_log() }}'

on-run-end:
  - '{{ dq_tools.store_test_results(results) }}'

# models:
#   dq_tools:
#     +enabled: true

# dbt docs generate && dbt docs serve
# metrics:
#   dq_tools:
#     +enabled: true